spring.application.name=client-service
spring.r2dbc.url=r2dbc:postgresql://localhost:5435/client_db
spring.r2dbc.username=chief
spring.r2dbc.password=root

# ????????????????? ???? ????? schema.sql
spring.sql.init.mode=always

# ????????????
logging.level.org.springframework.r2dbc=DEBUG