CREATE TABLE subscriptions (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    product_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    event_type VARCHAR(65),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);